In [54]:
import pandas as pd 


In [55]:
data = pd.read_csv('rawData/PA.csv')
resData = pd.read_csv('cleanData/OHE_PA.csv')
data.head()

major_department       year  \
0  Engineering (if you're computer science choose...  Sophomore   
1                                           Sciences  Sophomore   
2  Engineering (if you're computer science choose...  Sophomore   
3  Engineering (if you're computer science choose...  Sophomore   
4  Engineering (if you're computer science choose...  Sophomore   

         music_genre      living          humour sports  \
0                Rap  Off-Campus     Situational    Yes   
1                Pop  Off-Campus  Dad-Joke Humor     No   
2                Pop  Off-Campus     Situational     No   
3  Indie/Alternative  Off-Campus      Dark-Humor     No   
4                EDM  Off-Campus      Dark-Humor    Yes   

              friday_night                         school_balance  \
0         Watching Netflix  5-8 hours of school and/or work a day   
1  At a party/With Friends  5-8 hours of school and/or work a day   
2                 Studying   8+ hours of school and/or work a day   
3         Watching Netflix   8+ hours of school and/or work a day   
4                  Working   8+ hours of school and/or work a day   

  entertainment_genre  
0              Comedy  
1       Anime/Cartoon  
2             Rom-Com  
3           Emotional  
4       Anime/Cartoon

In [56]:
type_data = data["year"].to_list()
type_data

['Sophomore',
 'Sophomore',
 'Sophomore',
 'Sophomore',
 'Sophomore',
 'Senior',
 'Sophomore',
 'Senior',
 'Sophomore',
 'Sophomore',
 'Junior',
 'Freshman',
 'Alumni',
 'Junior',
 'Senior',
 'Sophomore',
 'Sophomore',
 'Senior',
 'Sophomore',
 'Sophomore',
 'Freshman',
 'Junior',
 'Sophomore',
 'Sophomore',
 'Sophomore',
 'Sophomore',
 'Sophomore',
 'Sophomore',
 'Sophomore',
 'Sophomore',
 'Junior',
 'Junior',
 'Senior',
 'Sophomore',
 'Freshman',
 'Junior',
 'Sophomore',
 'Freshman',
 'Sophomore',
 'Sophomore',
 'Sophomore']

In [57]:
import numpy as np

conditions =  ['major_department', 'year', 'music_genre', 'living', 
'humour', 'sports','friday_night','school_balance','entertainment_genre']

def strings_to_onehot():
    result = pd.DataFrame()
    for i in range(len(conditions)):
        categories_column = data[conditions[i]].to_list()
        unique_categories = list(set(categories_column))
        one_hot_matrix = np.zeros( (len(categories_column), len(unique_categories)), dtype=int )
 
        for row, category in zip(one_hot_matrix, categories_column):
            category_index = unique_categories.index(category)
            row[category_index] = 1
        
        cur_res = pd.DataFrame(columns = unique_categories, data = one_hot_matrix)
        print(cur_res[unique_categories].values)
        result[unique_categories] = cur_res[unique_categories]
        result.to_csv('cleanData/OHE_PA.csv')
    return result

onehot_types = strings_to_onehot()

print("-------OUTSIDE METHOD ---------")
onehot_types.head()
# onehot_types.to_csv('cleanData/OHE_PA.csv')


[[0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]]
[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]
[[0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0

Business  Engineering (if you're computer science choose this)  Sciences  \
0         0                                                  1            0   
1         0                                                  0            1   
2         0                                                  1            0   
3         0                                                  1            0   
4         0                                                  1            0   

   Junior  Alumni  Sophomore  Freshman  Senior  Blues  \
0       0       0          1         0       0      0   
1       0       0          1         0       0      0   
2       0       0          1         0       0      0   
3       0       0          1         0       0      0   
4       0       0          1         0       0      0   

   I don’t listen to music  ...  8+ hours of school and/or work a day  Action  \
0                        0  ...                                     0       0   
1                        0  ...                                     0       0   
2                        0  ...                                     1       0   
3                        0  ...                                     1       0   
4                        0  ...                                     1       0   

   Anime/Cartoon  Drama/K-Drama  Comedy  Horror  Rom-Com  Documentary  Sci-Fi  \
0              0              0       1       0        0            0       0   
1              1              0       0       0        0            0       0   
2              0              0       0       0        1            0       0   
3              0              0       0       0        0            0       0   
4              1              0       0       0        0            0       0   

   Emotional  
0          0  
1          0  
2          0  
3          1  
4          0  

[5 rows x 47 columns]